# Generated by Django 4.2.11 on 2024-04-05 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_remove_production_report_fg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_fg',
            name='FG_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.finishgoods'),
        ),
        migrations.AlterField(
            model_name='production_rm',
            name='RM_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.rawmaterial'),
        ),
    ]
