# Generated by Django 4.2.10 on 2024-02-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finish_good_name', models.CharField(max_length=50)),
                ('Fg_qty', models.IntegerField()),
                ('Fg_Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_genrate', models.DateTimeField()),
                ('Totall_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.sales_party')),
                ('sales_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountant.salesitem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_genrate', models.DateTimeField()),
                ('Totall_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchase_party')),
                ('sales_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountant.salesitem')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_party_name', models.CharField(max_length=50)),
                ('paid_date', models.DateField()),
                ('amt_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.sales_party')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_party_name', models.CharField(max_length=50)),
                ('paid_date', models.DateField()),
                ('amt_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchase_party')),
            ],
        ),
        migrations.CreateModel(
            name='MisCExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_genrate', models.DateTimeField()),
                ('Totall_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('P_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchase_party')),
                ('S_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.sales_party')),
                ('sales_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountant.salesitem')),
            ],
        ),
        migrations.CreateModel(
            name='debtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('D_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.sales_party')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountant.salesbill')),
            ],
        ),
        migrations.CreateModel(
            name='creditors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('C_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.purchase_party')),
                ('Purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountant.purchasebill')),
            ],
        ),
    ]
